AWSTemplateFormatVersion: 2010-09-09
Description: Initial Setup for EC2 Deployment - Test Environment
Parameters:
  Env:
    Type: String
    Description: Environment Type
    Default: test
    AllowedValues:
      - test
      - prod
Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Env
          Value: !Sub ${Env}

  subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: vpc
      CidrBlock: 172.16.0.0/24
      AvailabilityZone: ap-south-1a
      Tags:
      - Key: Env
        Value: !Sub ${Env}

  ig:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Env
        Value: !Sub ${Env}

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpc
      InternetGatewayId: !Ref ig

  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group of Test Environments
      SecurityGroupIngress:
        - Description: permit SSH
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - Description: permit All TCP 
          IpProtocol: '-1'
          FromPort: 0
          CidrIp: 0.0.0.0/0
          ToPort: 65535
      Tags:
        - Key: Env
          Value: !Sub ${Env}
      VpcId: !Ref vpc
      
Outputs:
  subnetId:
    Description: Subnet Id
    Value: !Ref subnet
    Export:
      Name: !Sub "${Env}-subnet"
  vpdId:
    Description: VPC Id
    Value: !Ref vpc
    Export:
      Name: !Sub "${Env}-vpc"
  securityGroupId:
    Description: Security Group for Test Env
    Value: !Ref securityGroup
    Export:
      Name: !Sub "${Env}-sg"