---
- name: update web servers
  hosts: all
  remote_user: root

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
